### ISSUE TITLE
Does Samsa support v2 STAT tables?

### ISSUE THREAD

**Issue by m4rc1e** [Lorp/samsa#21]
I have a font which needs [format 4](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-table-format-4) Axis value tables since the font contains multiple axes. In order to use this format, the STAT table must be v2.

I've attached the font.
[Inconsolata[wdth,wght].ttf.zip](https://github.com/Lorp/samsa/files/4376209/Inconsolata.wdth.wght.ttf.zip)

Just an fyi to others, MS Office doesn't support v2 either.

**Comment by Lorp** [comment]
This font does not need format 4 Axis values tables, as far as I can tell. All your SemiBolds are at 600, all your UltraExpandeds are at 200, etc. In other words, the instances in the design space are on an orthogonal grid, and therefore you need 17 (=8+9) Axis values tables in format 1, 2 or 3 (see table), rather than 72 (=8*9) in format 4. You in fact have 76 Axis value tables including 4 duplicates (e.g. AxisValue indices 2 and 70, both UltraExpanded ExtraLight).

| axisIndex | name | value |
| ---- | --- | --- |
| 0 | ExtraLight | 200 |
| 0 | Light | 300 |
| 0 | (Regular) | 400 |
| 0 | Medium | 500 |
| 0 | SemiBold | 600 |
| 0 | Bold | 700 |
| 0 | ExtraBold | 800 |
| 0 | Black | 900 |
| 1 | UltraCondensed | 50 |
| 1 | ExtraCondensed | 62.5 |
| 1 | Condensed | 75 |
| 1 | SemiCondensed | 87.5 |
| 1 | (Regular) | 100 |
| 1 | SemiExpanded | 112.5 |
| 1 | Expanded | 125 |
| 1 | ExtraExpanded | 150 |
| 1 | UltraExpanded | 200 |

BTW you mean format v1.2, which is the latest on the [Microsoft STAT spec](https://docs.microsoft.com/en-us/typography/opentype/spec/stat) and in your font.

In any case, I should still support Format 4 :)

**Comment by Lorp** [comment]
Do you know if MS Office rejects all format v1.2 STAT tables, or only the Format 4 Axis value tables inside them? /cc @robmck-ms

**Comment by Lorp** [comment]
The samsa-core.js STAT parser does work with Format 4, in case you want to hack. Type `GLOBAL.vf.tables["STAT"].data` into the console to see the data. Here’s an extract from Inconsolata[wdth,wght].ttf:

![Screenshot 2020-03-24 at 18 50 39](https://user-images.githubusercontent.com/587440/77453973-9e1d5800-6e00-11ea-8428-992c826a6a50.png)

**Comment by Lorp** [comment]
Related, a couple of weeks ago @twardoch wrote an interesting post about non-orthogonality and STAT, [googlefonts-discuss, Re: Variable fonts: Do we really need so many instances](https://groups.google.com/d/msg/googlefonts-discuss/XCHD21yi4KI/96J81yyQDAAJ), referring to @typoland’s nice diagram in his repo [Instances Calculator](https://github.com/typoland/InstancesCalculator/).

<img width="633" alt="exp01" src="https://user-images.githubusercontent.com/587440/77455241-467fec00-6e02-11ea-996d-72eb1a39cce6.png">

**Comment by robmck-ms** [comment]
On Windows, I recommend using FontSetViewer (https://github.com/fdwr/FontSetViewer) to see how the various APIs are enumerating the font. I agree that this font doesn't need format 4 - that format was created for something like DecoVar where the instances don't really group in any particular way, and the axes are more visual parameters.

Regarding office: The responsibility for STAT is below Office. For font enumeration, Office calls GDI, which relies on DirectWrite for much of the work, but also does it's own STAT table parsing. DWrite supports format 4; GDI doesn't yet.

**Comment by robmck-ms** [comment]
Ugh. I can't keep up with all the threads on all the discussion forums. The intention of the weight axis user coordinates is that they *are* orthogonal and you use avar to map them to whatever normalized coordinate you want to get the right interpolation you want. Unfortunately, avar has it's problems... (cue XVARr/ avar2, all of which I wanted to get into the original v1.8 spec, but...)

**Comment by Lorp** [comment]
All good. The check of what Format 4 was doing, using your sample font, made me see a bug where it wasn’t being parsed correctly :) Now, here are the first two records from Inconsolata in Samsa’s `font.tables["STAT"].data`. In formats 1, 2 and 3 `axisIndex` and `value` are numeric, in format 4 they are arrays of numerics.

<img width="225" alt="Screenshot 2020-03-24 at 20 14 52" src="https://user-images.githubusercontent.com/587440/77462478-d62a9800-6e0c-11ea-9b23-b0b3bb3091f3.png">

I’ll leave the issue open until Samsa GUI supports Format 4.

**Comment by davelab6** [comment]
> The intention of the weight axis user coordinates is that they _are_ orthogonal and you use avar to map them to whatever normalized coordinate you want to get the right interpolation you want. 

Should this clarification be added to the ot spec?

> Unfortunately, avar has it's problems...

Where are these documented? :)

**Comment by robmck-ms** [comment]
>

> > The intention of the weight axis user coordinates is that they _are_ orthogonal and you use avar to map them to whatever normalized coordinate you want to get the right interpolation you want.
> 
> Should this clarification be added to the ot spec?

Perhaps. It's broader than the wght axis. All axes are supposed to be independent axes (e.g. you can hold all axes constant and move one and only the feature that one controls should move). With wght, there's the added constraint that the numbers correspond to specific semantics. 400 is Regular, 700 is Bold, etc.  So, if you set to wght=700, that should be the bold for whatever you have the rest of the axes set to. (or, flipside: if you keep wght=700, and move other stuff, you should always get the Bold of whatever the other axes are set to, and moving wght to 400 gives you the corresponding Regular). 

So, my what I described in my previous message is implicit in the details, but this is clearly something people are stumbling on. (I've seen wdth axes that have 100 as bold and 0 as light).

> > Unfortunately, avar has it's problems...
> 
> Where are these documented? :)

https://github.com/Microsoft/OpenType-XVAR-proposal#the-problem plus discussions in several places about XVAR & avar2.

**Comment by Lorp** [comment]
Samsa GUI now supports format 4 axisValueTables, from this commit d8830ee096ea588009f129358c08ba9e284cadff

Also in that commit, the STAT panel now gets amended as you move around the designspace.
