### ISSUE TITLE
Interface oddities

### ISSUE THREAD

**Issue by arialcrime** [Lorp/samsa#25]
While using Samsa (thanks a lot for this handy tool!) I came across 2 small things that I wanted to share.

1. In the Axes section I can select and edit the values on the very right, but putting something else in there and hitting Enter does not do anything. Should it? 

2. Working on a [4 axes font](https://github.com/undercasetype/Fraunces/tree/master/fonts) the Instances section gets a bit difficult to handle with half the values disappearing to the right. Sure, I can get to them by scrolling. Maybe it would be really nice if there’s a little more space for the sidebar?

**Comment by Lorp** [comment]
Thanks for this. Manual entry is on my todo list. At the same time I also want to add increment/decrement buttons, to add/subtract the smallest possible value (so ±1/65536 for user values, ±1/16384 for normalized values).

**Comment by Lorp** [comment]
You’re right that the instances section is not very usable for fonts with many axes. I’m thinking about how to improve this. Making the sidebar expandable might be the easiest solution, but still, there are fonts with 16+ axes… Ideas welcome.

**Comment by Lorp** [comment]
Updating axis locations now works via editing the current axis value. Also, new ‘nudge’ buttons on each axis increment/decrement the value by the smallest possible value. Commit is 3a2b5202a46f1159fb0d3ea9b27dfffb3b56a56b

**Comment by Lorp** [comment]
To see the usefulness of the ‘nudge’ buttons:
* load Skia
* select the Q glyph
* select normhex number format
* enter 2479 on the Weight axis
* press the + nudge button several times and watch the shape change

The location 0x2479 (2.2537 in  decimal user coordinates) is just before the two intermediate masters that control the morphing of the Q’s tail. The intermediate form at 0x247b is probably unintended. Using the nudge controls in this way can help find unwanted intermediate forms between closely adjacent masters.
