### ISSUE TITLE
Font menu

### ISSUE THREAD

**Issue by dberlow** [Lorp/samsa#30]
Please either 
   put the font menu at the top, or 
   do not open all the windows above it when a font is selected. 

it disappears. 

thanks

**Comment by Lorp** [comment]
Discussing this in issue #31. Will likely merge the “Fonts to load” panel with the “Info” panel as a dropdown, like Axis-Praxis. It’ll be at the top.

**Comment by Lorp** [comment]
Fixed in a1987dd29e2e5d015ba130065af17280f14e37ca
