### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by rememberlenny** [Lorp/samsa#41]
How would you feel about me porting this over to typescript to be easier to grok?

**Comment by Lorp** [comment]
Are you proposing a TypeScript fork or converting the main branch to TypeScript?

**Comment by rememberlenny** [comment]
I was hoping to encourage the main branch be converted to typescript. In the intermediate, having a typescript fork was a way to allow both to exist.

**Comment by rememberlenny** [comment]
Another way I would also break this up is to make the individual "parts" of samsa-core into separate files, and compile the entire file by brining the separate parts together.

**Comment by Lorp** [comment]
I’d need to think carefully before converting the main branch to TypeScript. One of the appealing aspects of Samsa is its lack of dependencies.

On separation, config stuff could be split off, SVG too, maybe by having a file that adds methods to the class prototypes. Is that the kind of direction you’re thinking? Maybe you could outline what the benefits would be. I feel it’s still small enough that it doesn’t need it for space optimization.

**Comment by rememberlenny** [comment]
Yes and yes.

The goal of the typescript shift is to codify the inputs of functions and return values, to be easier to understand. The typescript file would build into a javascript file, so for the end user, there is no difference. The typescript file is mainly for the developer.

Regarding separation, exactly. I think the functions you have in the samsa core seem useful outside of just this file. To be able to read a TTF file and get necessary headers, to turn a glyph into an SVG, to get the FVAR table, etc. All of that seems incredibly usable in other places.

**Comment by Lorp** [comment]
Closing this for now. No plans for this repo to switch to TypeScript.
