### ISSUE TITLE
Show STAT record version numbers

### ISSUE THREAD

**Issue by davelab6** [Lorp/samsa#43]
As an "inspector" tool, it would be helpful to know which version of a STAT table/record I am seeing :)

**Comment by Lorp** [comment]
Good idea, I’ll add it.

**Comment by Lorp** [comment]
Implemented in 124d57597019c80915e18b8c666fe23633187892

![Screenshot 2020-06-12 at 00 30 41](https://user-images.githubusercontent.com/587440/84441225-13e8d100-ac44-11ea-9c31-e405a2185e14.png)

**Comment by Lorp** [comment]
BTW the STAT table *record* versions are shown indirectly in the UI:

* format 1 have a note that shows the value, e.g. “200”
* format 2 have a note that also shows the range, e.g. “200 [200,250]”
* format 3 have a note that also shows the linked value, e.g. “0 (→ 1)”
* format 4 are always listed in the “Multiaxis” dropdown
