### ISSUE TITLE
Changes on interface (glyphs palette)

### ISSUE THREAD

**Issue by Omnibus-Type** [Lorp/samsa#45]
The panel for the Glyphs palette is too long for navigation. In animation mode is difficult to focus on the glyph being verified to advance to another glyph.

Some ideas to propose:
• Glyphs with components could be grouped
• The panel could be located as a floating window or located in another area of the interface, by example the bottom. Which would allow a wider palette to display more glyphs per row

Many thanks for the nice work!

**Comment by Lorp** [comment]
Glyphs panel is on the right now :)

You can control the order of panels and whether they are in the left or right container in `samsa-config.js`. I may add dragging later, but will close this issue now.
