### ISSUE TITLE
Implement composite matched points.

### ISSUE THREAD

**Issue by bungeman** [Lorp/samsa#55]
The TODO at https://github.com/Lorp/samsa/blob/42f44ad83de32a2742a4abd62689858d1894159f/src/samsa-core.js#L1795 should be fixed as it is nice to be able to fly multiple glyphs along a common path. This TODO probably persists due to a lack of examples for testing, so attaching a mostly minimal ttf file in a zip (since I cannot seem to be able to attach a ttf file directly) [VaryAlongQuad.zip](https://github.com/Lorp/samsa/files/5504063/VaryAlongQuad.zip).

**Comment by Lorp** [comment]
Thanks for raising this as an issue and for the excellent test font. Definitely needs to be fixed. I’ll get onto it when time allows.

**Comment by bungeman** [comment]
I think the font I attached to the issue report may be an older version. In any event a newer version and an explanation of how it was made can be had at https://bungeman.github.io/hoi.html .

**Comment by Lorp** [comment]
Fixed in dd25139393cfa0fb80208c54f8dc1bc57bdf1077

**Comment by Lorp** [comment]
https://user-images.githubusercontent.com/587440/103951307-528d2e00-5136-11eb-921a-f05a42e92f57.mp4
