### ISSUE TITLE
Samsa appears broken on OS X Chrome

### ISSUE THREAD

**Issue by m4rc1e** [Lorp/samsa#64]
If I drag and drop a vf, no glyphs appear.

<img width="1392" alt="Screenshot 2021-03-24 at 13 29 33" src="https://user-images.githubusercontent.com/7525512/112318550-0ff2e080-8ca5-11eb-8baf-ed9210ed2d70.png">

OS X 10.15.7, Chrome Version 89

I've attached the VF as well.

[samsa_test_font.zip](https://github.com/Lorp/samsa/files/6197577/samsa_test_font.zip)

**Comment by m4rc1e** [comment]
Cleared and I still get the same result. In the Chrome console, I get the following:

```
Uncaught ReferenceError: l is not defined
    at new globalThis.FontFace (<anonymous>:1:809)
    at new e.FontFace (hooks-frames-web.js:1)
    at new e.FontFace (hooks-frames-web.js:1)
    at SamsaFont.vfLoaded [as callback] ((index):956)
    at SamsaFont.parse (samsa-core.js:1217)
    at new SamsaFont (samsa-core.js:3233)
    at FileReader.reader.onload ((index):3623)
```

**Comment by Lorp** [comment]
What are `hooks-frames-web.js` and `anonymous`? They are nothing to do with Samsa.

**Comment by m4rc1e** [comment]
Apologies my bad. It appears that Samsa isn't working with the Chrome extension https://github.com/gildas-lormeau/SingleFile

**Comment by gildas-lormeau** [comment]
@m4rc1e I guess you probably don't care about it but this issue will be fixed in the next version of SingleFile.
