### ISSUE TITLE
svgPath() method not working like GUI

### ISSUE THREAD

**Issue by tomasdev** [Lorp/samsa#70]
I have a variable font of icons that have a FILL axis. When trying the same combination of axes values in the inspector (https://lorp.github.io/samsa/src/samsa-gui.html) I get the proper result. When doing it via code, it seems to glitch some curves.

From GUI:
<img width="517" alt="Screen Shot 2022-01-20 at 7 35 18 PM" src="https://user-images.githubusercontent.com/364033/150444307-d947d5da-5f0d-4c38-b285-3fa7b2e5a203.png">

From svgPath():
```
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 960 960">
  <path fill="#000" d="M446 271L521 271L521 438L689 438L689 513L521 513L521 689L446 689L446 513L271 513L271 438L446 438ZM480 61Q391 61 314.5 93Q238 125 181.5 181.5Q125 238 93 314.5Q61 391 61 480Q61 569 93 645.5Q125 722 181.5 778Q238 834 314.5 866.5Q391 899 480 899Q569 899 645.5 866.5Q722 834 778 778Q834 722 866.5 645.5Q899 569 899 480Q899 391 866.5 314.5Q834 238 778 181.5Q722 125 645.5 93Q569 61 480 61M480 153Q344 153 248.5 248.5Q153 344 153 480Q153 615 248.5 711Q344 807 480 807Q615 807 711 711Q807 615 807 480Q807 344 711 248.5Q615 153 480 153M480 139Q620 139 720.5 239Q821 339 821 480Q821 620 720.5 720.5Q620 821 480 821Q339 821 239 720.5Q139 620 139 480Q139 339 239 239Q339 139 480 139"/>
</svg>
```
<img width="162" alt="Screen Shot 2022-01-20 at 7 46 10 PM" src="https://user-images.githubusercontent.com/364033/150445280-589dc454-18ef-46cc-9fb9-537fb2893fad.png">

Any tips, pointers?

**Comment by tomasdev** [comment]
FWIW this is how I generate the SVG:
```
function getSvgPathData(font, glyph, tuple) {
  const instance = font.instances[0];

  if (!instance) {
    throw new Error('SamsaFont was not able to fetch font instances.');
  }

  let iglyph;

  instance.tuple = tuple;

  if (glyph.numContours < 0) {
    iglyph = glyph.decompose(instance.tuple, undefined);
  } else {
    iglyph = glyph.instantiate(null, instance, undefined);
  }

  const viewbox = getViewbox(iglyph);

  return `<svg xmlns="https://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 ${viewbox.width} ${viewbox.height}">
    <path d="${iglyph.svgPath()}"/>
  </svg>`
}
```

**Comment by tomasdev** [comment]
Turns out these lines are important (and the reason for the difference)

```
  if (font.featureVariations) {
    let substituteGlyphId = glyph.featureVariationsGlyphId(tuple);
    if (substituteGlyphId !== undefined) {
      glyph = font.glyphs[substituteGlyphId];
    }
  }
```

**Comment by Lorp** [comment]
Glad your sorted it out. Let me know if you have recommendations for improving the API.

BTW I’m glad to have taken a look at your SVG. It seems that Samsa is not closing subpaths using "Z", when its last point is off-curve. It’s important to use "Z" in all cases in case the path is stroked, otherwise you get end-cap rather than join effects.
