### ISSUE TITLE
samsa-core: Different tuple produce the same svgPath

### ISSUE THREAD

**Issue by wentin** [Lorp/samsa#77]
# Issue
See Gif: https://giphy.com/gifs/4PtGgwFQ661nWBaDVs/fullscreen
The top font works perfectly. It has the default axis values of [0, 0]. However, when I reproduce the font with a different default, the axis with the default value not set to 0 stopped working. Different tuple will produce the same svgPath.

# Code
I isolated the issue into a simpler Codepen:
https://codepen.io/wentin/pen/podwdBy?editors=0011

However, when I use the Samsa web app to test these two fonts, these two fonts both work perfectly! I am wondering what you did differently in the Samsa web app? What have i missed?

# Fonts:
[fonts.zip](https://github.com/Lorp/samsa/files/8051283/fonts.zip)

**Comment by Lorp** [comment]
I think the solution is quite simple: in heart_1.ttf, the default is indeed at [0,0] but the other master is at [-1,0] not [1,0]. The instances at [0,0] and [1,0] are identical, because max = default for that axis. If you switch the Number format in the Axis panel to “norm”, you’ll see the correct values for each font.

**Comment by wentin** [comment]
@Lorp thanks for responding! I don't think i understand, the default axes value of heart_1.ttf is [100, 0], and the other master  are [0, 0], [0, 100], [100, 100], how does it convert to tuple [-1, 0]?W
Where do I switch the Number format in axis panel to "norm", is it a Glyphs?

**Comment by Lorp** [comment]
I’m talking about the Axes panel in Samsa web app.

In heart_1.ttf, min=0, default=100, max=100. This is normalized to min=-1, default=0, max=0. That‘s the VF normalization rules!

**Comment by wentin** [comment]
I see, I impemented the wrong normalization rules and get the wrong tuple! Thanks! When i change the tuple to [-1, 0], it starts to generate different svgPath from [0, 0].
Many thanks!

**Comment by Lorp** [comment]
If you look at the “basic normalization” code [here](https://github.com/Lorp/samsa/blob/55cbd42408ffec4c58e71e3ee99dc94dcab7a52b/src/samsa-core.js#L3027-L3092) you’ll see the actual conversion code.
