### ISSUE TITLE
Does not report font axes after subsetting variable font

### ISSUE THREAD

**Issue by strarsis** [Lorp/samsa#89]
Variable fonts that were subsetted using `pyftsubset` are reported by sama as not having font axes.
Other tools like [this](https://wakamaifondue.com/) report font axes for the subsetted font file.

**Comment by strarsis** [comment]
Steps to reproduce:
1. Get a variable font, in this example [`Open Sans` from Google Fonts](https://fonts.google.com/specimen/Open+Sans) (Download family; extract downloaded ZIP file `Open_Sans.zip`):

2. Subset the variable font file:
2.a. Using [`glyphhanger`](https://www.npmjs.com/package/glyphhanger):
`glyphhanger --formats=woff2 --LATIN --subset=./OpenSans-VariableFont_wdth,wght.ttf`
2.b. Alternatively using [`pyftsubset`](https://fonttools.readthedocs.io/en/latest/subset/) (used by `glyphhanger`):
`pyftsubset OpenSans-VariableFont_wdth,wght.ttf --flavor=woff2 --output-file="OpenSans-VariableFont_wdth,wght-subset.woff2" --unicodes="U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,\
  U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,\
  U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"`

3. Upload (as drag and drop) the original, full font file `OpenSans-VariableFont_wdth,wght.ttf` into [`Samsa tool`](https://www.axis-praxis.org/samsa/). Note that font axes are available.
4. Upload (as drag and drop) the subsetted font file `OpenSans-VariableFont_wdth,wght-subset.woff2` into [`Samsa tool`](https://www.axis-praxis.org/samsa/). Note that font axes are not available: `This font does not contain variation axes.`

**Comment by Lorp** [comment]
Samsa does not handle WOFF2 fonts. Please try again without the `--flavor=woff2` option, and use `.ttf` as suffix.

**Comment by strarsis** [comment]
@Lorp: Well, this explains it. IMHO the tool should show a warning/error that WOFF2 font is unsupported, hence the reported information being incorrect.

**Comment by Lorp** [comment]
Thanks. Regarding handy warnings, there’s already issue #81. And indeed, allowing WOFF2 is on my list too. I’ll get to both of these when I upgrade the entire GUI app to [Samsa Core v2](https://github.com/Lorp/samsa-core).
